--- #YAML:1.0
name:                Term-VT102-Boundless
version:             0.02
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Term::VT102:                   0
    Test::More:                    0.53
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
